### ISSUE TITLE
Comments display chronologically

### ISSUE THREAD

**Issue by orenmendelow** [yosefserkez/mailpals#18]
<img width="666" alt="Screenshot 2024-10-22 at 11 23 18 AM" src="https://github.com/user-attachments/assets/2271911b-23f3-4c10-9970-ac517868bdac">

Comments currently display in reverse chronological order, which requires us to read the comments conversation bottom-to-top. Should be top-to-bottom (chronological from top).

**Comment by 4till2** [comment]
I noticed this, agree, and is a good first issue! 

I'd also like if they can be threaded. So you can reply to a reply. (probably only one level deep). This will require a polymorphic relationship so comments can be associated with another comment. Ari spent did some good work like  this with Spoonjoy back in the day.

**Comment by omendelow** [comment]
Oh cool. A few questions:
1. do you want that reply-to-comment implemented with this issue or 1 thing at a time?
2. do you want comment replies collapsed or expanded by default after clicking on "Comments (2)"? a certain number and then "see more"?

**Comment by 4till2** [comment]
Chronology is straightforward. Just change the sort in the view, and controller. reply to comment will require some database migrations. If you want to give it a go feel free. Might be a good pair programming opportunity.

**Comment by omendelow** [comment]
Why do you think I chose chronology as my first issue to tackle! After I do that I'll take a swing at reply to comment.

**Comment by orenmendelow** [comment]
Issue closed with PR #22
