### ISSUE TITLE
Biweekly Delivery Option Out of Place in Group Delivery Settings

### ISSUE THREAD

**Issue by orenmendelow** [yosefserkez/mailpals#25]
When choosing group issue delivery frequency, biweekly is listed above weekly, despite belonging between weekly and monthly

![IMG_8929](https://github.com/user-attachments/assets/49b70ef2-d95f-49ee-bbc7-847be0cf294e)

**Comment by yosefserkez** [comment]
Easy fix. You got this @orenmendelow! Just make sure to default the selection to bi-weekly. That is the best default.

**Comment by orenmendelow** [comment]
Thank you! I had the thought that that's why it was placed first in the list, but I'm sure there's a way to have it in its correct position and still be the default.

**Comment by orenmendelow** [comment]
Completed with PR #27
